=== sergehall/webdev-coursework/frontend/public/sandbox/CS80/mod-5/nutrition.dtd
<!ELEMENT nutritionFacts (productName, servingSize, calories, fat, cholesterol, sodium, carbohydrates, protein)>
  <!ELEMENT productName (#PCDATA)>
  <!ELEMENT servingSize (#PCDATA)>
  <!ELEMENT calories (totalCalories, fromFat)>
  <!ELEMENT totalCalories (#PCDATA)>
  <!ELEMENT fromFat (#PCDATA)>
  <!ELEMENT fat (totalFat, saturatedFat)>
  <!ELEMENT totalFat (#PCDATA)>
  <!ATTLIST totalFat unit CDATA #IMPLIED>
  <!ELEMENT saturatedFat (#PCDATA)>
  <!ATTLIST saturatedFat unit CDATA #IMPLIED>
  <!ELEMENT cholesterol (#PCDATA)>
  <!ATTLIST cholesterol unit CDATA #IMPLIED>
  <!ELEMENT sodium (#PCDATA)>
  <!ATTLIST sodium unit CDATA #IMPLIED>
  <!ELEMENT carbohydrates (totalCarbs, fiber, sugars)>
  <!ELEMENT totalCarbs (#PCDATA)>
  <!ATTLIST totalCarbs unit CDATA #IMPLIED>
  <!ELEMENT fiber (#PCDATA)>
  <!ATTLIST fiber unit CDATA #IMPLIED>
  <!ELEMENT sugars (#PCDATA)>
  <!ATTLIST sugars unit CDATA #IMPLIED>
  <!ELEMENT protein (#PCDATA)>
  <!ATTLIST protein unit CDATA #IMPLIED>

=== sergehall/webdev-coursework/frontend/public/sandbox/CS80/mod-5/nutrition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nutritionFacts SYSTEM "nutrition.dtd">
<nutritionFacts>
  <productName>Grandma White's Cookies</productName>
  <servingSize>1 package</servingSize>

  <calories>
    <totalCalories>260</totalCalories>
    <fromFat>100</fromFat>
  </calories>

  <fat>
    <totalFat unit="g">11</totalFat>
    <saturatedFat unit="g">2</saturatedFat>
  </fat>

  <cholesterol unit="mg">5</cholesterol>
  <sodium unit="mg">210</sodium>

  <carbohydrates>
    <totalCarbs unit="g">36</totalCarbs>
    <fiber unit="g">2</fiber>
    <sugars unit="g">15</sugars>
  </carbohydrates>

  <protein unit="g">5</protein>
</nutritionFacts>
